### ISSUE TITLE
Crashes Steamdeck when used with Reshadeck

### ISSUE THREAD

**Issue by baconVritters** [JosVerheij/reshade-shaders#2]
Attempting to load the RGBFullToLimited.fx shader with the Reshadeck plugin for Decky causes the Steamdeck to crash in Game/Big Picture mode.

**Comment by baconVritters** [comment]
groarken's PR fixed my issue, the shader now works wonderfully with Reshadeck

**Comment by JosVerheij** [comment]
Thanks for submitting the issue. I'll take a look at pull request https://github.com/JosVerheij/reshade-shaders/pull/1 and incorporate the changes.
